server.port=8082

# MongoDB Database Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/kce_safeguard_main

# JWT Security Configurations (must match auth-service's secret key)
app.jwt.secret=9a4f94d94923f11d11e202532a2207612d2b56aa11e86a076757656d0283c713
app.jwt.expiration-ms=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=./uploads
